### ISSUE TITLE
Add description to projects

### ISSUE THREAD

**Issue by jarosluv** [wunsh/docdog-engine#10]
Hi there!

We need to add a description to the projects so that users can find out what kind of project needs to translate. Can you help us?

This is not a hard problem to solve:

- [x] 1. First let's add some tests for our feature:

```elixir
# test/docdog/editor/editor_test.exs

...

-    @update_attrs %{"name" => "Phoenix Documentation"}
+    @update_attrs %{"name" => "Phoenix Documentation", "description" => "New description"}

...

    test "update_project/2 with valid data updates the project", %{project: project} do
      assert {:ok, project} = Editor.update_project(project, @update_attrs)
      assert %Project{} = project
      assert project.name == "Phoenix Documentation"
+     assert project.description == "New description"
    end
...

```
```elixir
# test/docdog_web/controllers/project_controller_test.exs

...

-    project = insert(:project, user: user, name: "Elixir Documentation 1")
+    project = insert(:project, user: user, name: "Elixir Documentation 1", description: "Official documentation of Elixir language")

...

     test "lists main user projects", %{conn: conn} do
       conn = get(conn, project_path(conn, :index))
       assert html_response(conn, 200) =~ "Elixir Documentation 1"
+      assert html_response(conn, 200) =~ "Official documentation of Elixir language"
+
       assert html_response(conn, 200) =~ "Elixir Documentation 2"
+      assert html_response(conn, 200) =~ "No description"
+
       refute html_response(conn, 200) =~ "Another User Project"

...

    test "renders form", %{conn: conn} do
      conn = get(conn, project_path(conn, :new))
      assert html_response(conn, 200) =~ "New Project"
+     assert html_response(conn, 200) =~ "Description"
    end

...

```

- [x] 2. Run `mix test`. You'll see:

```
82 tests, 3 failures
```

Now you need to fix all of them. This is a real TDD.

- [x] 3. Run `mix ecto.gen.migration add_description_to_projects`. See one of another migrations in project and add body to the new one migration like there.

- [x] 4. Run `mix ecto.migrate` to apply the migration.

- [x] 5. Add new field to `schema` and `changeset` in Project module.
- [x] 6. Add changes to `project/_project` and `project/form` templates.

NB. In tests we want to output "No description" in case of empty description. To make it easy, simply add this function to `views/project_view.ex`:

```elixir
def description(project) do
  project.description || "No description"
end
```

And call it in template.

Good luck!

**Comment by nesaulov** [comment]
I would like to tackle this issue.

**Comment by MeLeRyZ** [comment]
Ok, let's start. :)
:+1:

**Comment by jarosluv** [comment]
@MeLeRyZ

Thanks for your efforts, but this issue is solved by @nesaulov in https://github.com/wunsh/docdog-engine/pull/27

Please, choose another issue and I can help with it!

**Comment by jarosluv** [comment]
@nesaulov 

Thanks so much!
You mustn't stop :)
