### ISSUE TITLE
Add proper license

### ISSUE THREAD

**Issue by sobolevn** [wunsh/docdog-engine#18]
We have to choose a license before the contributions start.
Because, that's a very important thing.

Depending on the license this software might not be considered `OSS`. 
Here's a good way to start: https://choosealicense.com/

I personally prefer `MIT`.

**Comment by jarosluv** [comment]
@sobolevn 

Thanks for your thoughts. I pondered about the license and will think some more.

I want a full free instrument with some copyrights to original name of Docdog. Maybe this point is provided by default with any type of license?

**Comment by sobolevn** [comment]
> The MIT License is a permissive license that is short and to the point. It lets people do anything they want with your code as long as they provide attribution back to you and don’t hold you liable.

**Comment by jarosluv** [comment]
@sobolevn 

Yes, I added MIT license for now. And just started to apply PRs. :tada:

Thanks for the help!
