### ISSUE TITLE
Change how deployments are made

### ISSUE THREAD

**Issue by sobolevn** [wunsh/docdog-engine#36]
Travis has a special way to handle deployments.
In our case it is a `script`: https://docs.travis-ci.com/user/deployment/script/

In this case we won't have any problems in deploying broken releases or deploying branches other than `master`.

PR is incoming.

**Comment by jarosluv** [comment]
@sobolevn 

Hello, Nikita! Glad to see you!

I love features that implemented in a proper way. Thanks for your fixes in travis config!
