### ISSUE TITLE
Add linting in CI

### ISSUE THREAD

**Issue by sobolevn** [wunsh/docdog-engine#38]
Right now `mix credo --strict` generates more than 160 issues.

`credo` must be a required step inside `travis`.
I will add it, and also fix existing linting issues.

PR is incoming.

**Comment by jarosluv** [comment]
@sobolevn 

How does `credo` work with `mix format`?  I pass all files through `mix format` before commit.

**Comment by sobolevn** [comment]
While `format` fixes only very obvious issues, `credo` goes deeper finding refactoring opportunities and inconsistencies. 

They are complimentary tools.
